### ISSUE TITLE
Api used in meal-catalogue

### ISSUE THREAD

**Issue by Abhijeetrkushwaha** [OlukaDenis/meal-catalogue#4]
I really loved this site and want to to if there is any recipe api you can refer to me.

**Comment by OlukaDenis** [comment]
Thanks @Abhijeetrkushwaha,
I used this [API](https://www.themealdb.com/api.php). You can check it out, it is straight forward and easy to understand.

**Comment by Abhijeetrkushwaha** [comment]
Thank you so much for this...will definately look forward for more awesome projects from you❤️

**Comment by OlukaDenis** [comment]
You're  welcome
